name: CI
on: [push, pull_request]
env:
  CI: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  DEPLOY_NODE_VERSION: 20.x
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: git checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry/cache
          key: ${{runner.os}}-node${{matrix.node-version}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.os}}-node${{matrix.node-version}}-yarn-
      - name: Set up Node.js v${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - run: corepack yarn
      - run: corepack yarn test
      - run: corepack yarn lint
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: git checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: yarn cache
        uses: actions/cache@v4
        with:
          path: ~/.yarn/berry/cache
          key: ${{runner.os}}-node${{env.DEPLOY_NODE_VERSION}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: ${{runner.os}}-node${{env.DEPLOY_NODE_VERSION}}-yarn-
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.DEPLOY_NODE_VERSION}}
      - run: corepack yarn
      - run: corepack yarn semantic-release
